(function(){var f=window.sfx,j=window.cfx;j.radarVersion="7.2.5289.19355";var G=function a(){a._ic();this.d=this.e=null;this.a=0};j.bA=G;G.prototype={_0bA:function(){this.k();return this},getCircular:function(){return 0!=(this.a&4)},setCircular:function(a){this.b(4,a)},getClockwise:function(){return 0!=(this.a&32)},setClockwise:function(a){this.b(32,a)},getClosed:function(){return 0!=(this.a&8)},setClosed:function(a){this.b(8,a)},getFillArea:function(){return 0!=(this.a&2)},setFillArea:function(a){this.b(2,
a)},getShadows:function(){return 0!=(this.a&16)},setShadows:function(a){this.b(16,a)},getShowLines:function(){return 0!=(this.a&1)},setShowLines:function(a){this.b(1,a)},icX:function(){return 1},icY:function(){return 8397382},ieK:function(a){this.e=a},icW:function(a,c,b){switch(c){case 11:return this.j(b)}return null},icZ:function(a,c,b){a.a=1;a.b=0;var c=b.a.b.iaI(),l=b.m._nc();if(b.i.getVisible()){var m=new f.g,k=b.i.getLabelsCore();if(0!=k.Se()){var p=new f._p1(!1),k=k.iec(p,b.c,b.i.getFont(),
!1);m._cf(k)}else k=f.b.k(b.bf,"{0}",c),m._cf(b.c.idX(k,b.i.getFont()).e());l.m(-m.w,-m.h)}var g,e=new f._pN(0,0,0,0);j.bR.H(e,l,!0);k=e.a;p=e.b;m=e.c;g=e.d;m=f.a.o(m,1);g=f.a.o(g,1);var e=0!=(b.v&2),i=360/c,d=0,d=b.i.as()?e?45:i:b.i.getStep();this.getClockwise()||(i=-i,d=-d);l=this.o(b,k,p,m,g,l,d);if(G.m(b,k,p,m,g,d,l,this.getCircular())){var n=e?0:-90;g=l=!1;for(var h=d=0,q=b.r;q<=b.t;q++)if(b.d=q,b.aK(q),!b.g(8192)){var r=!1,u=0,s=0,z=0,v=0,B=0,D=0,A=0,C=b.K,H=b.H,y=m/(H-C);this.d=null;for(var w=
0;w<c;w++){b.e=w;b.az();b.P(!0);g=l;var x=b.w;e&&(n=this.getClockwise()?b.aV:-b.aV);n=new f._p1(n);j.bU.e(n);n=n.a;if(j.db.d(x))if(0==w)r=!0;else{if(!j.db.d(A)){var h=new f._p2(d,h),E=this.c(h,b,z,v,u,s,q,w,w-1,!0,k,p),d=h.a,h=h.b;if(!E&&(l=!0,0==(b.v&1)&&(g=!0),g))break}}else{if(x<=H&&x>=C){var x=x-C,F=E=0,F=E=x*y,s=new f._p2(u,s);j.bU.d(s,n,E,F,k,p);u=s.a;s=s.b;if(0!=w&&!j.db.d(A)){if(h=new f._p2(d,h),z=this.c(h,b,z,v,u,s,q,w,w-1,!1,k,p),d=h.a,h=h.b,!z&&(l=!0,0==(b.v&1)&&(g=!0),g))break}else 0==
w&&(B=u,D=s)}z=u;v=s;if(g)break}A=x;n+=i;b.at(0,0)}if(g)break;if(!j.db.d(A)){b.U=!1;b.az();b.P(!0);this.getClosed()||(B=u,D=s);A=new f._p2(d,h);u=this.c(A,b,u,s,B,D,q,b.e,b.e,r,k,p);d=A.a;h=A.b;if(!u){l=!0;break}b.at(0,0);!r&&0!=(this.a&8)&&(b.e=0,b.U=!1,b.az(),b.P(!0),r=new f._p2(d,h),this.c(r,b,B,D,B,D,q,0,0,!0,k,p),d=r.a,h=r.b,b.at(0,0))}}l?(b.d=d,b.e=h,a.b=0,a.a=a.b):(b.an-=c-1,b.e=b.q)}},o:function(a,c,b,l,m,k,p){var g=a.c,e=a.i,i=a.x(512),d=f.e._ca(3);d[0].x=c;d[0].y=b;var n=this.getCircular(),
h=this.getShadows(),q=a.bo()._nc(),r=f.a.d(360/p),u=0,s=0,z=0;h&&0!=q.a&&!i?(u=f.i(q.r,r+1),s=f.i(q.g,r+1),z=f.i(q.b,r+1)):(h=!1,u=s=z=0);var v=e.c.a,B=null,D=0!=(a.u&8),A=null,C=null,H=null;D&&(B=(new j.c5)._01c5("PlotArea"),A=e.aW(v),C=(new j.c5)._01c5(j.c_.Q(e,"Line",-1,!0)),H=(new j.c5)._01c5(j.c_.Q(a.h,"Line",-1,!0)));var y=(new f.ar)._0ar(q),w=a.i.L.c(f.m.b),x=a.h.L.c(f.m.b);n&&(h||g.idL(y,k.x,k.y,2*l,2*m));var E=v.o,F=null;E&&(F=a.a7(v,4));var v=e.getLabelsCore(),L=v.Se(),R=e.getFont(),i=i?
f.m.c():e.getTextColor()._nc(),t=0!=(a.v&2)?0:270,o=q._nc(),P=y;g.sidc(null);var N,I;I=new f._p2(0,0);j.bU.d(I,t,l,m,c,b);N=I.a;I=I.b;for(var M=0;M<r;M++){var J=e.getVisible();J&&(D&&g.sidc(e),G.n(a,r,v,L,R,i,N,I,t,M));t+=p;t=new f._p1(t);j.bU.e(t);var t=t.a,O=0,K=0,K=new f._p2(O,K);j.bU.d(K,t,l,m,c,b);O=K.a;K=K.b;d[1].x=N;d[1].y=I;d[2].x=O;d[2].y=K;this.getClockwise()&&j.bR.D(d[1],d[2]);h&&(P=(new f.ar)._0ar(o));D&&g.sidc(B);n?h&&g.idO(P,k,t-p,p):(g.idP(P,d),g.sidc(C),g.ids(w,N,I,O,K));h&&P._d();
if((0==M||E)&&J){var Q=J=null;if(0==M){if(Q=H,J=x,4==a.ak||0==a.ak)E?(Q=A,J=F):J=null}else Q=A,J=F;null!=J&&(g.sidc(Q),g.ids(J,c,b,N,I),0!=M&&g.sidc(A))}N=O;I=K;h&&(M>=f.i(r+1,2)?M==r?o._cf(q):o._cf(j.bR.d(q.a,o.r+u,o.g+s,o.b+z)):o._cf(j.bR.d(q.a,o.r-u,o.g-s,o.b-z)))}n&&(D&&g.sidc(C),g.idj(w,k.x,k.y,2*l,2*m));w._d();x._d();null!=F&&F._d();y._d();return r},c:function(a,c,b,l,m,k,p,g,e,i,d,n){var h=a=0;i||(c.aS(p,e,!0),this.getFillArea()&&(i=f.e._ca(3),i[0].x=b,i[0].y=l,i[1].x=m,i[1].y=k,i[2].x=d,i[2].y=
n,d=null,0!=(c.u&8)&&(d=c.c.idc(),null==this.d&&(n=(new j.bT)._0bT(c.bD,c.d,c.e,!0,!1,!1),n.h=!0,this.d=n),c.c.sidc(this.d)),c.c.idP(c.z,i),0!=(c.u&8)&&c.c.sidc(d)),this.getShowLines()&&c.c.ids(c.p,b,l,m,k));a=g;0>c.b.u?(h=-c.b.u,a+=h-1):h=f.a.o(c.b.u,1);0!=c.b.d&&0==a%h&&(0!=(c.v&192)&&c.au(c.d,e,!1)&&c.P(!0),c.aA(p,e),c.a6(b,l,0));c.c.sidc(null);c.b.a.b&&-1!=e&&c.aY((new f.e)._01e(b,l),e!=g,null);return!0},l:function(){null!=this.e&&this.e.iag(16777248)},k:function(){this.a=41},b:function(a,c){this.a=
c?this.a|a:this.a&~a;this.l()},j:function(a){a=a.a;a.e=8;0==a.b&&(a.b=4096);return null}};G.n=function(a,c,b,l,m,k,p,g,e,i){var d=0,n=0;270==e||90==e?d=1:90<=e&&270>=e&&(d=2);n=180<=e?2:0;e=null;e=0!=l?b.ied(i):0!=(a.v&2)?a.i.n.a(360*i/c)+"\u00b0":a.i.n.a(a.i.as()?i+1:i*a.i.aT());e=a.a5(a.i,e);c=(new j.cJ)._01cJ(k,d,n);c.l(a.c,m,e,(new f.e)._01e(p,g));c._d()};G.m=function(a,c,b,l,m,k,p,g){var e=a.K,i=a.H;if(e>=i)return!1;var d=a.h,n=d.j;if(0==(n&64)&&(d.as()&&d.calculateStep(a.a,a.c,m,!0),m=d.aT(),
n=0==(n&1),0<m)){var h=d.n,q=d.getFont(),r=a.x(512),u=d.getLabelsCore(),s=u.Se(),z=r?f.m.c():d.getTextColor()._nc(),v=d.c.a,r=v.o,B=a.a7(v,4),z=(new j.cJ)._01cJ(z,0,0),D=l/(i-e),A=a.c.idX(h.a(a.H),q).e().h,C=0!=(a.u&8),H=null;C&&(H=d.aW(v));for(var v=0!=v.p,y=0,w=0,x=e+m;x<=i;x+=m){var E=270,F=0,L=0,L=F=(x-e)*D;if(5>f.a.d(F-l))break;r&&g&&(C&&a.c.sidc(H),a.c.idj(B,c-L,b-L,2*L,2*L));for(var G=0;G<=p;G++){var t=0,o=0,o=new f._p2(t,o);j.bU.d(o,E,F,L,c,b);t=o.a;o=o.b;if(0!=G)if(r&&!g)C&&a.c.sidc(H),a.c.ids(B,
y,w,t,o);else break;else if(n&&(y=null,0!=s?(y=j.bU.a((x-e)/d.U+0.1),y=u.ied(y)):y=h.a(x),y=a.a5(d,y),C&&a.c.sidc(d),z.l(a.c,q,y,(new f.e)._01e(t+4,o-f.i(A,2)))),v)C&&a.c.sidc(H),a.c.ids(B,t-2,o,t+2,o);E+=k;y=t;w=o}}z._d();B._d()}return!0};G._dt("GR",f.Sy,0,j.icV,j.ieJ)})();
