(function(){var s=window.cfx,f=window.sfx,z={Version:"7.2.5289.19355"};s.funnel=z;var t=function A(){A._ic();this.b=this.c=0};t.prototype={_0dM:function(j,b){j.x==b.x?(this.b=j.x,this.c=f.D.e):(this.b=(b.y-j.y)/(b.x-j.x),this.c=b.y-this.b*b.x);return this},a:function(j){return 0==this.b?0:f.D.h(this.c)?this.b:(j-this.c)/this.b}};t._dt("CWGF",f.Sy,0);var j=function b(){b._ic();this.q=null;this.v=!1;this.g=this.h=this.b=null;this.a=this.t=this.e=this.f=0;this._0_1()};z.Funnel=j;j.prototype={_0_1:function(){this.p=
4;this.c=5;this.k=30;this.n=10;this.d=this.u=!0;this.o=this.l=!1;this.m=(new s.Line)._01_2(9);this.E();return this},getConic:function(){return this.v},setConic:function(b){this.v=b;this.i()},getFaces:function(){return this.p},setFaces:function(b){this.p=f.a.o(b,3);this.i()},getLabelInside:function(){return this.l},setLabelInside:function(b){this.l=b;this.i()},getLabelLine:function(){return this.m},getLabelLineAsSeries:function(){return this.o},setLabelLineAsSeries:function(b){this.o=b;this.i()},getSeparation:function(){return this.c},
setSeparation:function(b){this.c=b;this.i()},getTemplate:function(){return null==this.b?"":this.b.v()},setTemplate:function(b){null==b?this.b=null:(null==this.b&&(this.b=(new s._Zt)._0_Zt()),this.b.sv(b))},getTipHeight:function(){return this.k},setTipHeight:function(b){this.k=b},getTipWidth:function(){return this.n},setTipWidth:function(b){this.n=b},G:function(){},reset:function(){},icX:function(){return 1},icY:function(){return 142622977},ieK:function(b){this.q=b;this.m.ieK(this.q)},icW:function(b,
c,a){switch(c){case 4:return 1;case 11:return this.z(a);case 12:return!0}return null},icZ:function(b,c,a){b.a=1;b.b=0;var h=a.g(256);h&&(a.ba=!0);b=a.a.b.iaI();c=a.m._nc();c.w-=a.a.p;c.y+=a.a.p;c.h-=a.a.p;if(a.b.a.b&&!this.l){for(var g=0,d=0;d<b;d++){a.I=a.ag.getItem(a.d,d);var j=a.bC(),j=a.c.idX(j,a.ad).w,g=f.a.o(g,j)}g+=8;2!=a.b.a.h&&(c.x+=g);c.w-=g}var g=c.h,j=c.w,m=(g-this.c*(b-1))*c.w/2,n=g/j,e=983040|a.b.n,i=!1;h?i=!0:(e|=134217728,i=!1);0!=this.c&&(e|=3145728);var k=0,p=0,r=0,d=0;this.d?(k=
-g,p=-1,r=c.c(),d=c.y):(k=g,p=1,r=c.y,d=c.c());var l=new s.ba,q=new s.ba;l.b=c.x;l.a=d+p*this.c;l.c=0;q.b=c.g();q.a=r-p*this.c;q.c=a.a.f;var B=f.i(c.g()+c.x,2);this.d&&90<a.f.ib6()||!this.d&&90>=a.f.ib6()?(a.C=-1,a.n=b-1,a.e=a.n,a.q=0):(a.C=1,a.n=0,a.e=a.n,a.q=b-1);var h=h?this.p:4,o=0,v=0,u=a.L,t=a.R;if(t){for(d=u=0;d<b;d++)a.au(a.d,d,!1),o=a.ag.getItem(a.d,d)*a.aW,u+=o;if(0==u)return}a.bm=u;this.F(a,c);for(d=a.bd=0;d<b;d++){a.az();if(t){if(0==a.aW){a.at(0,1);continue}a.I*=a.aW;v+=a.I}else v=a.T;
a.a4=v;if(0!=a.I&&1.0E108!=a.I){0>a.C?(this.u?o=g-v/u*g:(o=m-v*m/u,o=f.a.u(f.a.d(2*o*n))),q.a=l.a-p*this.c,l.a=r+p*o):(this.u?o=v/u*g:(o=v*m/u,o=f.a.u(f.a.d(2*o*n))),l.a=q.a+p*this.c,q.a=r+p*o);var o=this.d?c.y-q.a:c.c()-q.a,x=0;a.g(33554432)&&(x|=1);a.au(a.d,a.e,!1);a.P(!0);a.aA(a.d,a.e);var y=e;d==b-1&&(y|=3145728);i?this.v?a.f.ib$(a.c,l,q,a.z,a.p,null,y,x,k,o):a.f.icl(a.c,l,q,a.z,a.p,null,y,x,k,o,h):this.B(a.c,l._nc(),q._nc(),x,k,o,a);o=a.I/u;a.b.a.b&&this.C(a,j,g,l,q,B,r,o,c);a.bd=v}a.at(0,1)}this.G(a,
c);a.an-=b-1;a.e=a.q;null!=this.b&&this.b._dispose1(!1)},F:function(b,c){var a=f.i(c.x+c.g(),2),h=this.n*c.w/100;this.f=a-h/2;this.e=a+h/2;a=c.h-this.c*(b.a.b.iaI()-1);this.a=c.c()-a*this.k/100;this.t=b.bm*this.k/100;a=this.d?c.y:c.c();this.h=(new t)._0dM((new f.e)._01e(c.x,a),(new f.e)._01e(this.f,this.a));this.g=(new t)._0dM((new f.e)._01e(c.g(),a),(new f.e)._01e(this.e,this.a))},E:function(){if(void 0!=s._Zt){var b=s.eO.h("Funnel",!0);null!=b&&this.setTemplate(b)}},D:function(b,c){var a=!1,h=c[0].y,
g=c[2].y,d=c;if(b.bd<this.t||0==b.bm){if(h<this.a&&c[2].x==c[3].x)return d=f.e._ca(6),d[0]._i1(this.g.a(h),h),d[1]._i1(this.h.a(h),h),d[2]._i1(this.h.a(this.a),this.a),d[3]._i1(d[2].x,g),d[5]._i1(this.g.a(this.a),this.a),d[4]._i1(d[5].x,g),d;c[0]._i1(this.f,h);c[1]._i1(this.e,h);a=!0}b.a4<this.t?(c[2]._i1(this.e,g),c[3]._i1(this.f,g)):a&&this.a<g?(d=f.e._ca(6),d[0]._i1(this.g.a(h),h),d[1]._i1(this.h.a(h),h),d[2]._i1(this.f,this.a),d[3]._i1(this.f,g),d[4]._i1(this.e,g),d[5]._i1(this.e,this.a)):(c[0]._i1(this.g.a(h),
h),c[1]._i1(this.h.a(h),h),c[2]._i1(this.h.a(g),g),c[3]._i1(this.g.a(g),g));return d},C:function(b,c,a,h,g,d,w,m,n){if(!b.R){var e=new s.ba,m=b.b.a._nc(),i=m.h,k=m.f;b.g(256)&&(i=0);switch(k){case 0:e.a=this.d?g.a:h.a;break;case 2:e.a=this.d?h.a:g.a;break;default:e.a=f.i(h.a+g.a,2)}h=b.bC();this.l?1!=i?(n=j.j(e.a-w,f.i(c,2),a),e.b=(this.d?0==i:2==i)?d-n:d+n,e.b=2==i?e.b-f.i(b.aP,2):e.b+f.i(b.aP,2)):e.b=d:(d=k=0,2==i?(e.b=n.g(),d=-2,k=e.a>this.a?this.e:this.g.a(e.a),k+=4,i=0):(e.b=n.x,d=2,k=e.a>this.a?
this.f:this.h.a(e.a),k-=4,i=2),0!=this.m.d?(n=f.m.b._nc(),this.o&&n._cf(b.p.d()),n=this.m.c(n._nc()),b.c.ids(n,k,e.a,e.b+d,e.a),n._d()):e.b=k,k=1);e.c=f.i(b.a.f,2);e=b.f.ick(e);h=b.a5(b.h,h);n=0;m.i&&(n=4096);m=(new s.cJ)._02cJ(m.a._nc(),i,k,n);b.a8(m,h,e._nc());m._d()}},B:function(b,c,a,h,g,d,w){var m=null,n=null,m=n=null,e=0,i=0,k=0,p=0,r=0,l=0,q=0,e=l=i=e=0,p=new s.ba,r=new s.ba;p._cf(c);r._cf(a);n=s.ba._ca(4);m=s.ba._ca(4);s.ba._ca(4);p=f.i(c.b+a.b,2);r=f.i(c.a+a.a,2);l=f.i(c.c+a.c,2);h=0!=(h&
8);e=0!=(c.b+a.b&1);h&&(j.w(c,p,r),j.w(a,p,r),c.b>a.b&&(i=new f._p2(c.b,a.b),j.y(i),c.b=i.a,a.b=i.b),e&&a.a--);q=a.a-c.a;e=a.b-c.b;i=a.c-c.c;e=f.i(e,2);i=f.i(i,2);if(0!=g){var t=0,o=0,t=j.j(d,e,g),o=j.j(d,i,g),k=new f._p1(k);j.r(k,4,p,a.a,l,e-t,i-o,n,-1);k=k.a;t=j.j(d+q,e,g);o=j.j(d+q,i,g);d=new f._p1(k);j.r(d,4,p,c.a,l,e-t,i-o,m,-1)}else{d=new f._p1(k);j.r(d,4,p,a.a,l,e,i,n,a.b);for(l=0;4>l;l++)m[l]._cf(n[l]);for(l=0;4>l;l++)m[l].a=c.a}e=4;d=null;if(0!=g&&(d=f.e._ca(e),d[0].x=n[1].b,d[0].y=a.a,d[1].x=
n[3].b,d[1].y=a.a,d[2].y=c.a,d[2].x=m[3].b,d[3].x=m[1].b,d[3].y=c.a,h))for(l=0;l<e;l++)j.A(d[l],p,r);if(a.a!=c.a)if(d=this.D(w,d),c=f.d.b._nc(),null!=this.b){for(b=this.b.id().Sb();!0==b.SI();)switch(a=b.SK(),a.bA()){case "P":case "PointsPolygon":a.sa(d);break;default:this.b.m(a,w,this,c)}b=f.d.b._nc();this.b.r(w.c,b,1,0)}else b.idP(w.z,d),b.idw(w.p,d)},i:function(){null!=this.q&&this.q.iag(16777248)},z:function(b){b=b.a;0==b.b&&(b.b=1);0==b.c&&(b.c=1);return null},toString:function(){return"Funnel"}};
j.j=function(b,c,a){return f.i(b*c,a)};j.r=function(b,c,a,h,g,d,j,m,n){for(var e=0,i=0,k=0,p=k=i=0,r=0,l=0,q=0,c=f.a.o(f.a.d(c),2),c=f.a.p(c,4),q=2*f.a.c/c,p=f.a.t(q),r=f.a.i(q),i=1,e=k=0;e<c;e++)m[e].a=h,m[e].b=a+f.a.k(d*k+0.5),m[e].c=g+f.a.k(j*i+0.5),l=i*r+k*p,k=k*r-i*p,i=l;b.a=q;if(-1!=n){i=f.u.c;k=-1;for(e=0;e<c;e++)m[e].b>i&&(k=e,i=m[e].b);if(-1!=k)for(e=0;e<c;e++)m[e].b==i&&(m[e].b=n)}return c};j.w=function(b,c,a){var f=b.b;b.b=c+(a-b.a);b.a=a-(c-f)};j.A=function(b,c,a){var f=b.x;b.x=c+(a-b.y);
b.y=a-(c-f)};j.y=function(b){var c=b.a;b.a=b.b;b.b=c};j._dt("CWGF",f.Sy,0,s.icV,s.ieJ)})();
