(function(){var c=window.cfx,e=window.sfx,m={Version:"7.2.5289.19355"};c.heatmap=m;var l=function q(){q._ic();this.b=this.c=0;this._0_1()};m.ColorGradientStop=l;l.prototype={_0_1:function(){this.d=new e.m;this.a=new e.m;return this},getColor:function(){return this.d},setColor:function(c){c=e.m._t(c);this.d._cf(c);this.a._cf(c)},getOffset:function(){return this.c},setOffset:function(e){this.c=e}};l._dt("CWGC",e.Sy,0);var o=function r(){r._ic()};m.ColorGradientCollection=o;o.prototype={_0_1:function(){this.a=
(new e._L)._0_L();return this},getCount:function(){return this.a.Se()},getItem:function(e){return this.a.So(e)},setItem:function(e,a){this.a.sSo(e,a)},add:function(e){this.a.Si(e)},clear:function(){this.a.clear()},e:function(c){var a=this.a.Se(),d=this.a.So(0);if(c==d.b)return d.a;for(var b=1;b<a;b++){var h=this.a.So(b),f=h.b;if(f==c)return h.a;if(f>c)return b=f-d.b,a=(c-d.b)/b,c=(f-c)/b,d=d.a._nc(),h=h.a._nc(),e.m.j(d.r*c+h.r*a,d.g*c+h.g*a,d.b*c+h.b*a);d=h}return d.a},insert:function(e,a){this.a.Sl(e,
a)}};o._dt("CWGC",e.Sy,0);var p=function a(){a._ic();this.e=this.c=null;this.p=this.q=this.r=this.i=this.j=this.b=this.f=this.d=this.t=0;this._0_1()};m.HeatMap=p;p.prototype={_0_1:function(){this.a=(new o)._0_1();this.g=3;var a=new l;a.setColor(e.m.j(192,0,0));this.a.add(a);a=new l;a.setColor(e.m.j(0,192,0));this.a.add(a);this.h=60;this.u();void 0!==c.motif?c._Em("heatmap",this,arguments):1<=arguments.length&&this.setStyle(arguments[0]);return this},getGradientStops:function(){return this.a},iei:function(){return null},
ieh:function(){return!1},iej:function(){return!0},getLegendHeight:function(){return this.g},setLegendHeight:function(a){this.g=a},getTemplate:function(){return null==this.e?null:this.e.q},setTemplate:function(a){null==this.e&&(this.e=(new c._Zt)._0_Zt());this.e.sv(a)},k:function(a){return this.c.getAxisY().getDataFormat().a(a)},iem:function(){return this.m()?1:this.g},reset:function(){},icX:function(){return 1},ic3:function(){this.l();return!1},icY:function(){return 20480},_iCommands:function(){return!1},
icr:function(a){this.c=e.V.D(a,c.Chart);this.c.getLegendBox().getItemAttributes().getItemList(this.c.getSeries()).setVisible(!1);return!0},ien:function(){return!1},iek:function(){},ics:function(){return null},ic2:function(){return!0},getHighlightArgs:function(){return!1},ic4:function(){return!1},icZ:function(a,d,b){d=b.c;a.b=1;a.a=0;a=0!=(b.u&8);if(b.e==b.n&&b.d==b.r){0==this.j&&this.l();this.r=e.i(b.m.w,e.a.d(b.q-b.n)+1);this.t=e.i(b.m.h,e.a.d(b.t-b.r)+1);this.q=b.m.x;this.p=b.m.y;for(var h=!0,f=
this.a.getCount(),j=d.idc(),g=0;g<f;g++){var i=this.a.getItem(g),k=i.d._nc();if(a){var n=(new c.c5)._01c5("HeatMap"+g.toString());d.sidc(n);k=d.idd()._Gv("fill",k,null,0)}i.a._cf(k);i.b=i.c;0!=i.b&&(h=!1)}a&&d.sidc(j);if(h&&1<f){j=h=1/(f-1);for(g=1;g<f;g++)i=this.a.getItem(g),i.b=j,j+=h}}if(!(b.Q||b.w<this.b))if(g=b.h,h=b.i,f=e.a.k(g.valueToPixel(b.d)),g=e.a.k(g.valueToPixel(b.d+1)),i=e.a.k(h.valueToPixel(b.e+0.5)),h=e.a.k(h.valueToPixel(b.e+1.5)),!(g<f)){a&&(a=(new c.c5)._01c5(null),j=d.idb().ieA(b.c.idc()),
a.e=j.ieS(1),a.d=j.ieS(0),d.sidc(a));b=this.a.e((b.w-this.b)/this.j)._nc();b=(new e.ar)._0ar(b);a=(new e.d)._02c(i,f,h-i,g-f);if(null!=this.e){for(f=this.e.id().Sb();!0==f.SI();)switch(g=f.SK(),g.c){case "F":case "Fill":g.sa(b)}this.e.r(d,a,1,0)}else d.idS(b,a);b._d()}},ic1:function(){},icW:function(a,d,b){switch(d){case 11:return this.o(b);case 13:b.b=1}return null},iel:function(){this.d=0},ic5:function(){return!1},ieo:function(a,d,b,h,f){a.a=!0;f._cf(e.g.b);a=d.idX(this.k(this.f),b).e();this.m()&&
(d=d.idX(this.k(this.b),b).e(),this.i=e.a.o(a.w,d.w),a.w=2*this.i+this.h,a.w=0.8*h.w,this.h=a.w-2*this.i);return a},iep:function(a,d){a.a=null;var b=0==this.d?this.f:this.b;a.b=0==this.d||this.d==this.g-1?this.k(b):" ";a.c=null;a.d=this.d;var h=this.m(),b=this.g;h&&(b=1);if(this.d>=b)return!1;d.b.d=0;if(0==this.d){var f=d.G,c=d.G+b*d.aP-d.A,g=d.ai;d.c.sidc(null);var b=new e.c,i=new e.e,k=new e.e;h?(g+=this.i,k._i1(g,f),i._i1(g+this.h,f),b._i2(g,f,this.h,c-f+2)):(g-=6,i._i1(g,f),k._i1(g,c),b._i2(g,
f+1,16,c-f-2));f=(new e.aC)._0aC(i,k,this.a.getItem(1).a,this.a.getItem(0).a);c=this.a.getCount();if(2<c){for(var g=(new e.ax)._01ax(c),i=e.m._ca(c),k=Array(c),n=0;n<c;n++){var l=this.a.getItem(c-1-n),m=n;i[m]._cf(l.a);k[m]=1-l.b}g.sb(i);g.sc(k);f.sk(g)}d.c.idR(f,b);f._d();f=this.c.iK(3)._nc();f=(new e.ao)._01ao(f);d.c.idB(f,b);f._d();h&&(h=new e.at,h.sd(1),f=d.b.a.d,c=(new e.ar)._0ar(d.b.a.a),g=e.i(b.y+b.c(),2),d.c.idG(a.b,f,c,b.g()+4,g,h),i=this.k(this.b),h.sb(2),d.c.idG(i,f,c,b.x-4,g,h),a.b="",
c._d(),h._d())}this.d++;return!0},u:function(){if(void 0!=c._Zt){var a=c.eO.h("HeatMap",!0);null!=a&&this.setTemplate(a)}},m:function(){var a=this.c.getLegendBox().ibO();return 3==a||1==a},l:function(){var a=this.c.getAxisY(),d=a.getLabels();d.clear();d.add("");for(var b=this.c.getSeries().Sb();!0==b.SI();){var c=b.SK().getText();null==c&&(c="");d.add(c)}a.setMin(d.Se()-1);a.setMax(0);a.setLabelValue(1);a.setStyle(a.j|512);this.b=e.D.c;this.f=e.D.d;a=this.c.q;d=a.iaN();b=a.iaI();for(c=0;c<d;c++)for(var f=
0;f<b;f++){var j=a.getItem(c,f);1.0E108!=j&&(this.b=e.a.p(this.b,j),this.f=e.a.o(this.f,j))}this.j=this.f-this.b},o:function(a){a=a.a;a.e=8;0==this.j&&this.l();a.f=this.b;a.g=this.f;0==a.b&&(a.b=35);return null}};p._dt("CWGH",e.Sy,0,c.icq,c.icV,c.ic0,c.ieg,c.i_n)})();
