(function(){var f=window.sfx,g=window.cfx;g.surfaceVersion="7.2.5289.19355";var l=function b(){b._ic();this.a=this.f=this.l=this.b=this.d=null;this.e=this.g=!1;this.p=this.k=this.c=0};g.by=l;l.prototype={_0by:function(){return this},getColors:function(){return this.b},setColors:function(b){null==b?this.b=null:(this.b=f.m._ca(b.length),b.Sd(this.b,0));this.j(560)},iei:function(){return null},iej:function(){return null!=this.d?this.d.iT().j==this:!1},ieh:function(){return!1},getShowContourLines:function(){return this.g},
setShowContourLines:function(b){this.g=b;this.o()},getShowGridLines:function(){return this.e},setShowGridLines:function(b){this.e=b;this.o()},getStep:function(){return 0>this.c?0:this.c},setStep:function(b){this.c=b;this.j(560)},i:function(){return null==this.b||0==this.b.length},h:function(b,c,a){0>=this.c&&(this.c=-b.aT(),0<=this.c&&(this.c=-f.a.d((a-c)/10)));return f.a.d(this.c)},n:function(b,c,a,e,f,g){if(this.g&&!this.e)for(var j=0;j<e;j++){var h=(j+1)%e;a[h].a==a[j].a&&a[j].a==f&&c.icb(b,g,
a[h].b,a[h].a,a[h].c,a[j].b,a[j].a,a[j].c)}},v:function(b,c,a,e,i,t,j){if(!(-1==e||-1==i||-1==t||-1==j)){var h=b.f,d=g.ba._ca(4),m=g.ba._ca(8),q=b.t<b.r?-1:1,s=b.k.c+g.bR.a(b.af,b.d,b.a.g),q=s-q*(b.af+f.i(b.af,b.a.g)+1);d[0].b=a;d[0].a=i;d[0].c=s;d[1].b=a;d[1].a=t;d[1].c=q;d[2].b=c;d[2].a=j;d[2].c=q;d[3].b=c;d[3].a=e;d[3].c=s;var i=d[0].a>d[1].a&&d[0].a>d[3].a&&d[2].a>d[1].a&&d[2].a>d[3].a||d[0].a<d[1].a&&d[0].a<d[3].a&&d[2].a<d[1].a&&d[2].a<d[3].a,j=b.h,n=b.K,l=b.H,x=this.h(j,n,l),r=b.y;this.t();
for(var u=0;u<this.k;u++){var o=this.q(u),o=(new f.ar)._0ar(o),v=this.e?this.f:(new f.ao)._0ao(o),w=this.g&&!this.e?this.f:null,n=n+x;n>l&&(n=l);var p=r,r=j.ab(b.a,n);p++;if(i){d[1].b=a;d[1].a=t;d[1].c=q;var k=g.bW.P(d,m,r,p,3);0!=k&&(h.icj(b.c,m,k,o,v),this.n(b.c,h,m,k,p,w));d[1].b=c;d[1].a=e;d[1].c=s;k=g.bW.P(d,m,r,p,3)}else k=g.bW.P(d,m,r,p,4);0!=k&&(h.icj(b.c,m,k,o,v),this.n(b.c,h,m,k,p,w));o._d();this.e||v._d()}}},q:function(b){if(this.i())return this.l.e();var c=this.b[b%this.b.length]._nc();
c.e()&&c._cf(this.d.iW(b%this.b.length));return c},iem:function(){var b=this.d.iT().p,c,a;a=new f._p2(0,0);b.V(a,!0);c=a.a;a=a.b;c=this.h(b,c,a);return f.a.h((b.o-b.l)/c)},icX:function(){return 1},icY:function(b){return 10==b?1079056136:1079064328},ieK:function(b){this.d=b},ien:function(){return!1},iek:function(){},icW:function(b,c,a){switch(c){case 11:return this.r(a);case 13:a.b=1,a.h=!0}return null},icZ:function(b,c,a){var e=c=0;if(a.aQ){if(null==this.a||this.a.length!=a.a.g+1)this.a=f.e._ca(a.a.g+
1);c=this.h(a.h,a.K,a.H);this.k=f.a.d(f.a.h((a.H-a.K)/c));0!=(a.u&8)&&(a.ba=!0)}0==a.d&&a.e==a.n&&(this.m(a.c,a.d,a.b.e,a.b.k._nc(),this.k),this.f=this.e||this.g?a.p.m():null);c=a.k.b;e=a.E?a.G:-1;if(a.E&&a.d!=a.r&&a.e!=a.n){var i=0,i=a.t<a.r?-1:1;this.v(a,c,this.a[a.d].x,e,this.a[a.d].y,this.p,this.a[a.d-i].y)}this.p=this.a[a.d].y;this.a[a.d].x=c;this.a[a.d].y=e;b.a=1;b.b=0;a.d==a.t&&a.e==a.q&&this.u()},iel:function(b,c,a){var e=this.iem();b.a=!0;c.r=e-1;c.t=0;a&&(b=new f._p2(c.r,c.t),g.bR.b(b),
c.r=b.a,c.t=b.b);c.l=a?1:-1;c.d=c.r-c.l;c.aK(0);a?this.m(c.c,0,c.b.e,c.b.k._nc(),e):this.m(c.c,0,c.b.k,c.b.e._nc(),e)},ieo:function(b,c,a,e,i){i._cf(f.g.b);e=this.d.iT().p;i=e.N();e=f.a.o(i.a(e.o).length,i.a(e.l).length);e=f.b.u(f.b.b,2*e,57);b.a=!0;return c.idX(e+" - ",a).e()},iep:function(b,c){b.b=null;b.a=b.b;b.c=null;b.d=-1;if(c.d==c.t)return!1;c.d+=c.l;b.d=c.d;var a=c.h,e=this.h(a,c.K,c.H),i=a.N(),g=new f.aQ,j=f.a.o(i.a(a.o).length,i.a(a.l).length),h=a.l+e*c.d,h=i.a(h),h=f.b.u(h,j,32);g.e(h);
g.e(" - ");h=a.l+e*(c.d+1);h=i.a(h);h=f.b.u(h,j,32);g.e(h);b.b=g.toString();c.b.d=0;c.b.e._cf(this.q(c.d));c.P(!0);return!0},m:function(b,c,a,e,f){this.i()&&(0!=(b.ic_()&8)&&(b=b.idd(),a=b._Gv("fill",a,"Attribute"+c,0),e=b._Gv("fill",e,"Attribute"+c+"Alt",0)),e.e()&&e._cf(g.bR.ae(a._nc(),0)),this.l=new g.b6(a,e,f))},o:function(){this.j(32)},j:function(b){null!=this.d&&this.d.iag(b|16777216)},u:function(){null!=this.f&&(this.f._d(),this.f=null)},t:function(){this.i()&&this.l.a()},r:function(b){b.a.e=
64;return null}};l._dt("GS",f.Sy,0,g.icV,g.ieg,g.i_n,g.ieJ)})();
