(function(){var u=window.cfx,b=window.sfx,S={Version:"7.2.5289.19355"};u.rose=S;var m=function v(){v._ic()};m.prototype={_0dN:function(){return this}};m.h=function(v){return v*b.a.c/180};m.f=function(v){return b.a.k(v+1.0E-13)};m.e=function(v,h,a){var g=0;a&&(h.w<h.h?(g=b.i(h.h-h.w,2),h.h=h.w,h.y+=g):(g=b.i(h.w-h.h,2),h.w=h.h,h.x+=g));h.w-=h.w%4;h.h-=h.h%4;v.c=b.i(h.w,2);v.d=b.i(h.h,2);v.a=b.i(h.g()+h.x,2);v.b=b.i(h.y+h.c(),2)};m.d=function(b){for(;360<=b.a;)b.a-=360;for(;0>b.a;)b.a+=360};m.a=function(v,
h,a,g,c,j){var f;f=new b._p2(0,0);m.b(f,h,a,g,c,j);h=f.a;f=f.b;v.b=b.a.k(f+0.5);v.a=b.a.k(h+0.5)};m.b=function(v,h,a,g,c,j){var f=m.h(h),h=b.a.t(f),f=b.a.i(f);0==h&&0==f&&(h=0,f=1);v.b=j+g*h;v.a=c+a*f};m.c=function(b,h){var a=b._nc();b._cf(h);h._cf(a)};m._dt("CWGM",b.Sy,0);var Q=function h(){h._ic();this.i=!1;this.c=this.f=0;this.h=!1;this.e=null;this.d=this.b=0;this.g=!1};Q.prototype={_0dO:function(){this.a=new b.e;return this},j:function(b){return this.i?this.f*b-this.d:-(this.d+this.f*b)}};Q._dt("CWGR",
b.Sy,0);var K=function a(){a._ic();this.a=this.b=null;this._0_1()};S.Rose=K;K.prototype={_0_1:function(){this.c=3;this.g=0;this.f=!0;this.e=90;this.u();return this},getCircular:function(){return 0!=(this.c&2)},setCircular:function(a){this.h(2,a)},getClockwise:function(){return 0!=(this.c&1)},setClockwise:function(a){this.h(1,a)},getInternalRadius:function(){return this.g},setInternalRadius:function(a){this.g=a},m:function(){return 0!=(this.c&4)},sm:function(a){this.h(4,a)},getSideBySide:function(){return this.f},
setSideBySide:function(a){this.f=a},getStartAngle:function(){return this.e},setStartAngle:function(a){this.e=a},getTemplate:function(){return null==this.b?null:this.b.v()},setTemplate:function(a){null==this.b&&(this.b=(new u._Zt)._0_Zt());this.b.sv(a)},k:function(a){return this.a.j(a)},reset:function(){},icX:function(){return 1},icY:function(){var a=33579536;this.f&&(a|=128);return a},icW:function(a,b,c){switch(b){case 11:return this.n(c)}return null},icZ:function(a,g,c){g=c.a.b.iaI();this.a=(new Q)._0dO();
this.a.f=360/g;this.a.i=this.getClockwise();this.a.d=this.e;if(null!=this.b&&null!=this.b.v()){this.a.g=!0;for(var j=this.b.id().Sb();!0==j.SI();)switch(j.SK().bA()){case "GT":case "GeometryTop":this.a.h=!0}}j=!1;0!=c.b.c&&(j=!0,this.a.e=Array(g));a.a=1;a.b=0;var f=c.m._nc();if(c.i.getVisible()){var i=new b.g,d=c.i.getLabelsCore();if(0!=d.Se()){var k=new b._p1(!1),d=d.iec(k,c.c,c.i.getFont(),!1);i._cf(d)}else d=b.b.k(c.bf,"{0}",g),i._cf(c.c.idX(d,c.i.getFont()).e());f.m(-i.w,-i.h)}var e;e=new b._pN(0,
0,0,0);m.e(e,f,!0);d=e.a;k=e.b;i=e.c;e=e.d;i=b.a.o(i,1);e=b.a.o(e,1);this.a.b=b.a.p(i,e);this.a.c=this.g*this.a.b/100;this.a.a._i1(d,k);k=0!=(c.v&2);d=0;d=0>=c.i.D?k?45:360/g:c.i.getStep();this.getClockwise()||(d=-d);f=this.t(c,f,d);if(this.p(c,d,f,this.getCircular())){f=!1;k=d=0;e=!1;for(var l=b.a.p(c.r,c.t),r=b.a.o(c.r,c.t);l<=r;l++)if(c.d=l,c.aK(l),!c.g(8192)){for(var n=c.K,D=c.H,s=(i-this.a.c)/(D-n),o=0;o<g;o++){c.e=o;c.az();c.au(c.d,c.e,!1);c.P(!0);c.aS(c.d,c.e,!1);var p=c.I,w=0;e&&(w=this.a.e[o],
p+=w);if(1.0E108==p)p=0;else if(p<=D&&p>=n&&!this.r(c,(w-n)*s,(p-n)*s,e)){d=l;k=o;f=!0;break}j&&(this.a.e[o]=p);c.at(0,1)}j&&(e=!0);if(f)break}f?(c.d=d,c.e=k,a.b=0,a.a=a.b):(c.an-=g-1,c.e=c.q);this.a=null}},u:function(){if(void 0!=u._Zt){var a=u.eO.h("Rose",!0);null!=a&&this.setTemplate(a)}},t:function(a,g,c){var j=a.c,f=a.i,i=a.x(512),d=b.e._ca(3);d[0]._cf(this.a.a);var k=this.getCircular(),e=this.m(),l=a.bo()._nc(),r=b.a.d(360/c),n=0,D=0,s=0;e&&0!=l.a&&!i?(n=b.i(l.r,r+1),D=b.i(l.g,r+1),s=b.i(l.b,
r+1)):(e=!1,n=D=s=0);var o=f.c.a,p=null,w=0!=(a.u&8),q=null,R=null,A=null;w&&(p=(new u.c5)._01c5("PlotArea"),q=f.aW(o),R=(new u.c5)._01c5(u.c_.Q(f,"Line",-1,!0)),A=(new u.c5)._01c5(u.c_.Q(a.h,"Line",-1,!0)));var I=(new b.ar)._0ar(l),z=a.i.L.c(b.m.b._nc()),O=a.h.L.c(b.m.b._nc());k&&!a.m_bDetecting&&!e&&(w&&j.sidc(p),j.idL(I,g.x,g.y,2*this.a.b,2*this.a.b));var E=o.o,H=null;E&&(H=a.a7(o,4));var o=f.getLabelsCore(),P=o.Se(),J=f.getFont(),i=i?b.m.c():f.getTextColor()._nc(),x=0!=(a.v&2)?0:270,t=l._nc(),
y=I;j.sidc(null);var B,F,C=new b._p2(0,0);m.a(C,x,this.a.b,this.a.b,this.a.a.x,this.a.a.y);B=C.a;F=C.b;for(C=0;C<r;C++){var M=!a.m_bDetecting&&f.getVisible();M&&(w&&j.sidc(f),K.q(a,r,o,P,J,i,B,F,x,C));x+=c;x=new b._p1(x);m.d(x);var x=x.a,N=0,G=0,G=new b._p2(N,G);m.a(G,x,this.a.b,this.a.b,this.a.a.x,this.a.a.y);N=G.a;G=G.b;d[1].x=B;d[1].y=F;d[2].x=N;d[2].y=G;this.getClockwise()&&m.c(d[1],d[2]);if(!a.m_bDetecting&&(e&&(y=(new b.ar)._0ar(t)),w&&j.sidc(p),k?e&&j.idO(y,g,x-c,c):(j.idP(y,d),j.sidc(R),j.ids(z,
B,F,N,G)),e&&y._d(),(0==C||E)&&M)){F=B=null;if(0==C){if(F=A,B=O,4==a.ak||0==a.ak)E?(F=q,B=H):B=null}else F=q,B=H;if(null!=B){var M=this.a.a.x,L=this.a.a.y;0!=this.a.c&&(L=new b._p2(M,L),m.b(L,x,this.a.c,this.a.c,this.a.a.x,this.a.a.y),M=L.a,L=L.b);j.sidc(F);j.ids(B,M,L,N,G);0!=C&&j.sidc(q)}}B=N;F=G;e&&(C>=b.i(r+1,2)?C==r?t._cf(l):t._cf(b.m.k(l.a,t.r+n,t.g+D,t.b+s)):t._cf(b.m.k(l.a,t.r-n,t.g-D,t.b-s)))}k&&!a.m_bDetecting&&(w&&j.sidc(R),j.idj(z,g.x,g.y,2*this.a.b,2*this.a.b));z._d();O._d();null!=H&&
H._d();I._d();return r},r:function(a,g,c,j){var f=this.a.c,i=(new b.aA)._0aA(),d=0,k=0;0==f?(d=a.b.x/100,k=(1-d)/2):(d=1,k=0);1!=a.aa&&(d/=a.aa,k+=a.ab*d);var e=this.k(a.e+k),l=this.k(a.e+k+d),d=(e+l)/2,r=new b.f,n=new b.f,m=new b.f,s=new b.f,o=2*f,p=this.a.a.x-f,w=this.a.a.y-f,k=new b.f;m._cf(this.d(e,0));s._cf(this.d(l,0));var q=this.d(d,0)._nc();k._cf(this.d(d,c));var u=m.x-s.x,A=m.y-s.y;r._i1(k.x+u/2,k.y+A/2);n._i1(k.x-u/2,k.y-A/2);0!=g&&(q._cf(this.d(d,g)),m._i1(q.x+u/2,q.y+A/2),s._i1(q.x-u/
2,q.y-A/2));q=null;this.a.h&&(q=(new b.aA)._0aA());0!=f?(j?(i.q(r,n),i.q(n,s),i.q(s,m)):(i.f((new b.d)._02c(p,w,o,o),l,e-l),i.q(m,r),i.q(r,n)),i.B(),null!=q&&q.q(r,n)):(f=2*c,j?(i.g(this.a.a.x-g,this.a.a.y-g,2*g,2*g,e,l-e),i.g(this.a.a.x-c,this.a.a.y-c,f,f,l,e-l)):(i.t(this.a.a.x,this.a.a.y,s.x,s.y),0<c&&i.g(this.a.a.x-c,this.a.a.y-c,f,f,l,e-l),i.B()),null!=q&&q.g(this.a.a.x-c,this.a.a.y-c,f,f,l,e-l));if(this.a.g){g=b.d.b._nc();for(j=this.b.id().Sb();!0==j.SI();)switch(e=j.SK(),e.bA()){case "G":case "Geometry":e.sa(i);
break;case "GT":case "GeometryTop":e.sa(q);break;case "SizeItem":e.sa(2*c);break;case "XItem":e.sa(this.a.a.x-c);break;case "YItem":e.sa(this.a.a.y-c);break;default:this.b.m(e,a,this,g)}this.b.r(a.c,g,1,0)}else a.c.idN(a.z,i),a.c.idu(a.p,i);if(a.m_bDetecting&&a.detectCheck())return a.v&=-2,!1;i._d();null!=q&&q._d();a.b.a.b&&(c=a.c.idf(),i=new b.aE,i.f(d+90,k),a.c.sidf(i),a.aY((new b.e)._01e(k.x,k.y),!1,null),a.c.sidf(c));return!0},p:function(a,g,c,j){var f=a.K,i=a.H;if(f>=i)return!1;var d=a.h,k=d.j;
if(0==(k&64)&&!a.m_bDetecting){0>=d.D&&d.calculateStep(a.a,a.c,this.a.b,!0);var e=b.a.d(d.D),k=0==(k&1);if(0<e){var l=d.n,r=d.getFont(),n=a.x(512),D=d.getLabelsCore(),s=D.Se(),o=n?b.m.c():d.getTextColor()._nc(),p=d.c.a,n=p.o,w=a.a7(p,4),o=(new u.cJ)._01cJ(o._nc(),0,0),q=(this.a.b-this.a.c)/(i-f),K=a.c.idX(l.a(a.H),r).e().h,A=0!=(a.u&8),I=null;A&&(I=d.aW(p));for(var p=0!=p.p,z=0,O=0,E=f+e;E<=i;E+=e){var H=270,P=0,J=0,J=P=(E-f)*q+this.a.c;if(5>b.a.d(P-this.a.b))break;n&&j&&(A&&a.c.sidc(I),a.c.idj(w,
this.a.a.x-J,this.a.a.y-J,2*J,2*J));for(var x=0;x<=c;x++){var t=0,y=0,y=new b._p2(t,y);m.a(y,H,P,J,this.a.a.x,this.a.a.y);t=y.a;y=y.b;if(0!=x)if(n&&!j)A&&a.c.sidc(I),a.c.ids(w,z,O,t,y);else break;else if(k&&(z=null,0!=s?(z=m.f((E-f)/d.U+0.1),z=D.ied(z)):z=l.a(E),z=a.a5(d,z),A&&a.c.sidc(d),o.l(a.c,r,z,(new b.e)._01e(t+4,y-b.i(K,2)))),p)A&&a.c.sidc(I),a.c.ids(w,t-2,y,t+2,y);H+=g;z=t;O=y}}o._d();w._d()}}return!0},d:function(a,g){return this.o(new b._p2(0,0),a,g)},o:function(a,g,c){g=g*b.a.c/180;a.a=
b.a.t(g);a.b=b.a.i(g);c+=this.a.c;g=this.a.a.x+c*a.b;a=this.a.a.y+c*a.a;return(new b.f)._01e(g,a)},h:function(a,b){this.c=b?this.c|a:this.c&~a},n:function(a){a.a.e=8;return null}};K.q=function(a,g,c,j,f,i,d,k,e,l){var m=0,n=0;270==e||90==e?m=1:90<=e&&270>=e&&(m=2);n=180<=e?2:0;e=null;e=0!=j?c.ied(l):0!=(a.v&2)?a.i.n.a(360*l/g)+"\u00b0":a.i.n.a(0>=a.i.D?l+1:l*b.a.d(a.i.D));e=a.a5(a.i,e);g=(new u.cJ)._01cJ(i._nc(),m,n);g.l(a.c,f,e,(new b.e)._01e(d,k));g._d()};K._dt("CWGR",b.Sy,0,u.icV)})();
